### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by JakeyPrime** [ChipWolf/zendesk-discord-webhook-bot#1]
I know it's a longshot, given the age of the last update, but given how it's basically the only thing on the market right now, is there any chance of updating this? 

I would kill to have something up to date to keep track of the updates to my tickets in Discord.

Thanks in advance, :)

**Comment by ChipWolf** [comment]
Sure

**Comment by ChipWolf** [comment]
@JakeyPrime what specifically did you want me to do here?

**Comment by JakeyPrime** [comment]
Hey there,
Sorry for the delay, the current functionality is fine but it was ultimately a pain to get setup, and I still didn't succeed at it. 

Maybe because I'm using Python 3.8 as Ubuntu 20 has kicked support for 2.7. 

But it was issue after issue to get it running on Python 3. If you'd like I can try getting it installed again and give you the errors. I'm somewhat familiar with Python but not enough to be comfortable to apply changes. 

Appreciate anything you can do for me!

**Comment by ChipWolf** [comment]
@JakeyPrime that'd be appreciated. I've asked Zendesk to provide me with an instance for testing with some demo data so I can get back into this. I no longer use Zendesk as Atlassian provided our team with their suite for free which included Service Desk.

**Comment by JakeyPrime** [comment]
They should offer a demo but I'll get it up and running for you and get some errors. Our tickets are not exactly super private so I'd be happy to use ours to test anything you might want to test. This is far from a "production" environment.

**Comment by ChipWolf** [comment]
@JakeyPrime bit unconventional, but could you contact me on Discord `ChipWolf#0001` and I'll be more than happy to support you there

**Comment by JakeyPrime** [comment]
I was honestly completely hoping you would say that. Not sure why I didn't put the pieces together as this is a webhook for Discord haha. I'm `JakeyPrime#0001`

**Comment by ChipWolf** [comment]
That's a friend request sent @JakeyPrime
